apiVersion: v1
kind: Service
metadata:
  labels:
    app: temporal-demo
  name: temporal-demo
  namespace: temporal
spec:
  type: NodePort
  ports:
    - name: "temporal-demo-service"
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: temporal-demo
