apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: temporal-demo
  name: temporal-demo
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-demo
  template:
    metadata:
      labels:
        app: temporal-demo
    spec:
      containers:
        - name: temporal-demp
          image: fadhilrasendriya/temporal-io-demo:0.0.2
          ports:
            - containerPort: 8080
              name: temporal-demo
          env:
            - name: TEMPORAL_HOST
              value: 192.168.100.50
            - name: PAYMENT_HOST
              value: 192.168.100.50